environment:
  MSYSTEM: MINGW64
install:
  - git submodule update --init --recursive
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm --needed -Sy git mingw-w64-x86_64-cmake mingw-w64-x86_64-qt5 mingw-w64-x86_64-libusb mingw-w64-x86_64-protobuf mingw-w64-x86_64-protobuf-c mingw-w64-x86_64-toolchain make"
  - xcopy /s /e C:\projects C:\msys64\home\appveyor

build_script:
  - C:\msys64\usr\bin\bash -lc "mkdir hidviz/build && cd hidviz/build && cmake -G ""Unix Makefiles"" .. && make"
